local f = io.open('hook.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 hook.sh')
os.execute('killall -9 tg')
os.execute('rm -rf hook.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('hook.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 hook.sh')
os.execute('screen ./hook.sh')
